FROM freckie/rpi-opencv-pytorch-python:3.8-buster

RUN apt-get -y update --allow-releaseinfo-change

RUN pip3 install --upgrade pip
RUN pip3 install urllib3
RUN pip3 install -U Pillow
RUN pip3 install Flask==1.1.2
RUN pip3 install flask_cors
RUN pip3 install imutils
RUN pip3 install datetime
RUN pip3 install tqdm
